### ISSUE TITLE
Item Tooltip Visibility

### ISSUE THREAD

**Issue by zzahkaboom24** [Offroaders123/Dark-Mode#4] opened 2021-11-20 01:18 UTC
Hi, i would have a feature request if possible, at the moment you deactivated the item names above the hotbar when using your texture pack so i would like to have an option on the texture pack to either enable or disable this (the usual texture pack settings that you know from fps boosters as an example giving you a slider with a description of what it does). I prefer this to show me a text above the hotbar e.g. when i have a pickaxe with and one without mending as its more convenient and I wouldnt have to change stuff around in hud_screen.json. If this is too hard you could put a very small guide for others on your mcpedl page what needs to be done in order for it to show. Thank you for your time

**Comment by Offroaders123** [comment] 2021-11-20 09:32
Oops, sorry about that! Looks like this is another bug that's come up. I didn't mean for the item tooltips to disappear, that's not the intended behavior. I have a little bit of UI code set up that brings the tooltips back to their look before the dark background was added, as I personally preferred that better. But, it looks like that doesn't work anymore. I will look into the issue and see if it can be fixed. If there's no way around it, I'll just remove the custom feature.

I plan to spend more time updating the pack once v1.18 Stable comes out, since more issues are probably going to come up. I will likely address this around then. In the meantime, you can get the tooltips back by deleting `hud_screen.json` altogether, as nothing else for Dark Mode is required in that file.

Thanks again for the bug report! I haven't been playing on Bedrock for a few months just to mix things up.

**Comment by Offroaders123** [comment] 2022-05-13 23:48
Alright, as of the last few days, this is now fixed! Thanks again for making a bug report about it.

**Closed as completed by Offroaders123** 2022-05-13 23:48 UTC
Labels: bug
